db:
  adapter: postgresql
  host: localhost
  port: 5432
  user:
  password:
  database: micro_auth
password:
  minimum_length: 8
secrets:
  secret_key_base: '1234567890'
rabbitmq:
  consumer_pool: 10
